print("This is a compilation of jokes!")
input("")
print("Knock, knock")
input("")
print("Who")
input("")
print("You didn't tell me you where an owl!!!!!!!")
print(r":)")
input("")
print("Here is the next joke")
input("")
print("Why did Albert Einstein cross the universe.")
input("")
print("To get to the same side!")