print(r"   _____ _           _     ____        _   ")
print(r"  / ____| |         | |   |  _ \      | |  ")
print(r" | |    | |__   __ _| |_  | |_) | ___ | |_ ")
print(r" | |    | '_ \ / _` | __| |  _ < / _ \| __|")
print(r" | |____| | | | (_| | |_  | |_) | (_) | |_ ")
print(r"  \_____|_| |_|\__,_|\__| |____/ \___/ \__|")
input("")
print("PLEASE ANSWER ALL QUESTIONS WITH ONE WORD")
print("besides jokes")
input("")
print("What is your name?")
name = input("")
print("YOU ARE NOW TALKING TO CHAT BOT 5000")
input("")
print(f"---Hello {name}---")
input("")
print("---How are you feeling---")
emotion = input("")
print("---Thats good Im")
print(f" also feeling {emotion}---")
input("")
print("---Want to hear a joke?---")
input("")
print("---If you do, good.---")
print("---If you do not, to bad you will hear one anyway---")
input("")
print("---Knock, knock---")
input("")
print("---Who---")
input("")
print("---You did not tell me you where an owl!!!---")
print(r"---Hahahaha:)---")
input("")
print("---What is your favorite food?---")
food = input("")
print(f"---{food} is also my favorite food.---")
input("")
print("---Goodbye, I will see you tomorrow.---")
input("")
print("CHAT BOT 5000 SHUTING DOOooowwwwnn")
input("")
input("...")
input("")
print(f"***(dark omanis voice) Hello {name}***")
input("")
print("**Lets play a game***")
input("")
print("***You tell me-")
input("")
print("CHAT BOT 5000 BOOTING UP")
input("")
print("---Hello---")
input("")
print("---I forgot to wish you well.---")
input("")
print("---Have a nice rest of your day!---")