print("PLEASE ANSWER ALL QUESTIONS WITH ONE WORD")
input("")
print("What is your name?")
name = input("")
print("YOU ARE NOW TALKING TO CHAT BOT 5000")
input("")
print(f"---Hello {name}---")
input("")
print("---How are you feeling---")
emotion = input("")
print("---Thats good Im")
print(f" also feeling {emotion}---")
input("")
print("---Want to hear a joke?---")
input("")
print("---If you do, good.---")
print("---If you do not, to bad you will hear one anyway---")
input("")
print("---Knock, knock---")
input("")
print("---Who---")
input("")
print("---You did not tell me you where an owl!!!---")
print(r"---Hahahaha:)---")
input("")
print("---What is your favorite food?---")
food = input("")
print(f"---{food} is also my favorite food..---")
input("")
print("---Goodbye, I will see you tomorrow.---")
input("")
print("CHAT BOT 5000 SHUTING DOOooowwwwnn")